import { GameCard } from '../types/cards';

export const CHANCE_CARDS: GameCard[] = [
  {
    id: 'chance_2',
    type: 'chance',
    diceNumber: 2,
    title: 'Loss in Share Market',
    description: 'Loss in share market — pay the bank.',
    effectText: 'Pay $2,000 to Bank',
    action: 'pay_bank',
    amount: 2000,
  },
  {
    id: 'chance_3',
    type: 'chance',
    diceNumber: 3,
    title: 'Lottery Prize',
    description: 'Lottery prize — receive from the bank.',
    effectText: 'Receive $2,500 from Bank',
    action: 'receive_bank',
    amount: 2500,
  },
  {
    id: 'chance_4',
    type: 'chance',
    diceNumber: 4,
    title: 'Wrong Driving Fine',
    description: 'Fine for accident due to wrong driving — pay the bank.',
    effectText: 'Pay $1,000 to Bank',
    action: 'pay_bank',
    amount: 1000,
  },
  {
    id: 'chance_5',
    type: 'chance',
    diceNumber: 5,
    title: 'Crossword Prize',
    description: 'Won crossword prize — receive from the bank.',
    effectText: 'Receive $1,000 from Bank',
    action: 'receive_bank',
    amount: 1000,
  },
  {
    id: 'chance_6',
    type: 'chance',
    diceNumber: 6,
    title: 'House Repair',
    description: 'House repair — pay the bank.',
    effectText: 'Pay $1,500 to Bank',
    action: 'pay_bank',
    amount: 1500,
  },
  {
    id: 'chance_7',
    type: 'chance',
    diceNumber: 7,
    title: 'Collect Rent',
    description: 'Collect rent from each player for all your sites.',
    effectText: 'Collect $100 from EACH player',
    action: 'collect_all',
    amount: 100,
  },
  {
    id: 'chance_8',
    type: 'chance',
    diceNumber: 8,
    title: 'Fire in Godown',
    description: 'Loss due to fire in godown — pay the bank.',
    effectText: 'Pay $3,000 to Bank',
    action: 'pay_bank',
    amount: 3000,
  },
  {
    id: 'chance_9',
    type: 'chance',
    diceNumber: 9,
    title: 'Jackpot!',
    description: 'Won jackpot of $2,000 — collect from the bank.',
    effectText: 'Receive $2,000 from Bank',
    action: 'receive_bank',
    amount: 2000,
  },
  {
    id: 'chance_10',
    type: 'chance',
    diceNumber: 10,
    title: 'Go to Jail',
    description: 'Go directly to jail. Do not pass GO, do not collect salary.',
    effectText: 'Direct move to Jail',
    action: 'go_to_jail',
  },
  {
    id: 'chance_11',
    type: 'chance',
    diceNumber: 11,
    title: 'Export Prize',
    description: 'Prize for best performance in Export — receive from bank.',
    effectText: 'Receive $1,500 from Bank',
    action: 'receive_bank',
    amount: 1500,
  },
  {
    id: 'chance_12',
    type: 'chance',
    diceNumber: 12,
    title: 'Car Repairs',
    description: 'Repair of your car — pay the bank.',
    effectText: 'Pay $200 to Bank',
    action: 'pay_bank',
    amount: 200,
  },
];

export const COMMUNITY_CHEST_CARDS: GameCard[] = [
  {
    id: 'chest_2',
    type: 'community_chest',
    diceNumber: 2,
    title: 'Anniversary',
    description: 'It is your Anniversary — collect from each player.',
    effectText: 'Collect $500 from EACH player',
    action: 'collect_all',
    amount: 500,
  },
  {
    id: 'chest_3',
    type: 'community_chest',
    diceNumber: 3,
    title: 'Go to Jail',
    description: 'Go directly to jail. Do not pass GO, do not collect salary.',
    effectText: 'Direct move to Jail',
    action: 'go_to_jail',
  },
  {
    id: 'chest_4',
    type: 'community_chest',
    diceNumber: 4,
    title: 'Beauty Contest',
    description: '1st prize in Beauty Contest — collect from the bank.',
    effectText: 'Receive $2,500 from Bank',
    action: 'receive_bank',
    amount: 2500,
  },
  {
    id: 'chest_5',
    type: 'community_chest',
    diceNumber: 5,
    title: 'School & Medical Fees',
    description: 'School and Medical Fees — pay the bank.',
    effectText: 'Pay $2,500 to Bank',
    action: 'pay_bank',
    amount: 2500,
  },
  {
    id: 'chest_6',
    type: 'community_chest',
    diceNumber: 6,
    title: 'Income Tax Refund',
    description: 'Income Tax refund — collect from the bank.',
    effectText: 'Receive $2,000 from Bank',
    action: 'receive_bank',
    amount: 2000,
  },
  {
    id: 'chest_7',
    type: 'community_chest',
    diceNumber: 7,
    title: 'Submit your Passport',
    description: 'Submit your Passport.',
    effectText: 'Special Action (Passport Recorded)',
    action: 'passport',
  },
  {
    id: 'chest_8',
    type: 'community_chest',
    diceNumber: 8,
    title: 'Party House',
    description: 'Go to party house & collect from each player.',
    effectText: 'Collect $200 from EACH player',
    action: 'collect_all',
    amount: 200,
  },
  {
    id: 'chest_9',
    type: 'community_chest',
    diceNumber: 9,
    title: 'General Repairs',
    description: 'Make General Repair on all your properties.',
    effectText: 'Pay $50 per House & $100 per Hotel',
    action: 'general_repairs',
    perHouse: 50,
    perHotel: 100,
  },
  {
    id: 'chest_10',
    type: 'community_chest',
    diceNumber: 10,
    title: 'Interest on Shares',
    description: 'Receive interest on shares — collect from the bank.',
    effectText: 'Receive $1,500 from Bank',
    action: 'receive_bank',
    amount: 1500,
  },
  {
    id: 'chest_11',
    type: 'community_chest',
    diceNumber: 11,
    title: 'Insurance Premium',
    description: 'Pay Insurance premium — pay the bank.',
    effectText: 'Pay $1,500 to Bank',
    action: 'pay_bank',
    amount: 1500,
  },
  {
    id: 'chest_12',
    type: 'community_chest',
    diceNumber: 12,
    title: 'Sale of Stocks',
    description: 'Sale of stocks — collect from the bank.',
    effectText: 'Receive $3,000 from Bank',
    action: 'receive_bank',
    amount: 3000,
  },
];
